spring.application.name=wifi_connection
spring.sql.init.separator=;
spring.sql.init.mode=always

# 🌟 DYNAMIC DOCKER-READY CONNECTION PROPERTIES
# Fallback options (after the ':') keep it working if you ever run it locally outside Docker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cable_billing_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:006942}

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

# Ensure Postgres uses the correct schema
spring.jpa.generate-ddl=true

# This ensures data.sql runs AFTER Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true

# App Pagination Defaults
app.pagination.default-page=0
app.pagination.default-size=1
app.pagination.default-sort=lastName